### PR TITLE
thank you alumni. text complete. needs review/approval

### PR DESCRIPTION
**Pull request by gseals**
- I couldn't the formatting of the poem to work.
- I created a div around the section to signify where it begins and is contained. Feel free to remove that.

Evan, could you break each line at the '/' and delete those items out afterwards?

### CODE REVIEW

**Comment by evangdesigns** [comment]
1) Well said.
2) Merge with the latest master
3) For the line-breaks in the poem:
  a) You can replace all `/` with a `<br />`. This is a literal line break in HTML.
  b) OR you can wrap each line in `<p>` tags. 
`<p>` tags have a larger top and bottom margin, so the stanzas will have larger vertical spacing from each other, and you may not like that styling. I leave it to you.
4) The formatting worked for me. What I would suggest, however, is going into `main.scss` and adjusting the left and right padding in the `.section` class to something like `5%` or `10%` to pull the text off the sides of the browser window.

**Comment by gseals** [comment]
@evangdesigns you're brilliant. I'll look at this tomorrow

**Comment by gseals** [comment]
@evangdesigns the  <br/> are perfect. I'll return and modify the left and right padding

**Comment by gseals** [comment]
@evangdesigns check me oooooooooooout. I updated the styling and fixed a word in one of the other thank yous. should we add padding to the back-end thank yous, also?

**Comment by evangdesigns** [comment]
👍

**Pull request merged**
